djPet/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import handler400, handler403, handler404, handler500
from django.urls import include, path, re_path
from .views import (
    home_page,
    contact_page,
    about_page,
    new_pricer_page,
    easter_egg_page,
    # page_not_found
)

urlpatterns = [
    path('home/', home_page),
    path('about/', about_page),
    re_path(r'^contacts?/$', contact_page),
    # path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
    path('pricer/', new_pricer_page),
    path('easter_egg/', easter_egg_page),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# handler400 = 'djPet.views.page_not_found'
# handler403 = 'djPet.views.page_not_found'
# handler404 = 'djPet.views.page_not_found'
# handler500 = 'djPet.views.error_500'

djPet/models.py
from django.db import models


class pricer(models.Model):
    document = models.FileField()
    shopID = models.CharField(max_length=1)
    name = models.CharField(max_length=1)
    amount = models.CharField(max_length=1)
    price = models.CharField(max_length=1)
    partNumber = models.CharField(max_length=1)
    MRP = models.CharField(max_length=1)
    # user_ID
    # operation_time

djPet/forms.py
# from django import forms
from django.forms import ModelForm
from .models import pricer

# def columnIndex(colunmDict: dict):
#     print('PriceChanger started, ', colunmDict)
#     """ Function takes a dictionary from block 'define needed information' and changing it to a list for
#     'fileChanger.py' """
#     # integerColunm = {'A': 0, 'B': 1, 'C': 2, 'D': 3, 'E': 4, 'F': 5, 'G': 6, 'H': 7, 'I': 8, 'J': 9, 'K': 10,
#     'L': 11,
#     #                  'M': 12, 'N': 13, 'O': 14, 'P': 15, 'Q': 16, 'R': 17, 'S': 18, 'T': 19, 'U': 20, 'V': 21,
#     #                  'W': 22, 'X': 23, 'Y': 24, 'Z': 25}
#     integerColunms = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's',
#                       't', 'u', 'v', 'w', 'x', 'y', 'z']
#     # shopID = colunmDict['shopID']
#     # name = colunmDict['name']
#     # amount = colunmDict['amount']
#     # price = colunmDict['price']
#     # partNumber = colunmDict['partNumber']
#     # MRP = colunmDict['MRP']
#     neededColumns = []
#     # print('before for loop')
#     token = colunmDict['csrfmiddlewaretoken']
#     for value in colunmDict.values():
#         if value != token:
#         # print(value)
#             if value in integerColunms:
#                 neededColumns.append(integerColunms.index(value))
#             else:
#                 neededColumns.append('Error: {} cannot be indexed'.format(value))
#     # print(neededColumns)
#
#     return neededColumns


class PricerForm(ModelForm):
    class Meta:
        model = pricer
        fields = [
            "shopID",
            'name',
            'amount',
            'price',
            'partNumber',
            "MRP"
        ]

djPet/views.py
from django.http import HttpResponse, Http404
from django.shortcuts import render
from django.core.files import File
from .forms import PricerForm
from .calculations import pricesCollector
from django.core.files.storage import FileSystemStorage



def home_page(request):
    # home_page_title = 'Request was formatted with .format method'
    return render(request, "home_page.html", {'title': 'this is really THE home page'})


def contact_page(request):
    return render(request, 'contacts.html', {'title': 'All sort of links'})


# def pricer_page(request):
#     """"""
#     print('request Post before everything: ', request.POST, request.FILES)
#     print('request without .POST', request)
#     if request.method == "POST":
#     # if request.method == "POST" and request.FILES['fileWithPrices']:
#         print('within IF and AND loop')
#
#         # print('after .Model definition ', form, pricer.document, 'shopID', pricer.shopID)
#         form = PricerForm(request.POST)
#         print('after form=pricerform()')
#         if form.is_valid():
#             print('inside if form is valid')
#             # form.save()
#             cleanedForm = form.cleaned_data
#             print(cleanedForm, cleanedForm['shopID'])
#         # if request.FILES:
#         #     print('within request.Files')
#         #     PriceChanger(request.FILES['file'])
#         print('before definition of the form')
#         # neededColumns = columnIndex(request.POST)
#         # print(neededColumns)
#         # pricer(document=request.FILES, shopID=neededColumns[0], name=neededColumns[1],
#         #        amount=neededColumns[2], price=neededColumns[3], partNumber=neededColumns[4],
#         #        MRP=neededColumns[5])
#         # print('Form before isvalid: ', form)
#         # if form.is_valid():
#         #     print(form.cleaned_data)
#         #     return render(request, 'pricer.html')
#         # else:
#         #     print('Wrong')
#         #     return render(request, 'pricer.html')
#         return render(request, 'pricer.html')
#     return render(request, 'pricer.html')



def new_pricer_page(request):
    template = "pricer.html"
    if request.method == "POST":
        form = PricerForm(request.POST)
        uploaded_file = request.FILES['document']
        # print(form)
        fs = FileSystemStorage()
        fs.save(uploaded_file.name, uploaded_file)
        print(uploaded_file.size)
        print(uploaded_file.content_type)
        if form.is_valid():
            print('inside if form is valid')
            cleanedData = form.cleaned_data
            neededColumns = []
            for i in cleanedData.values():
                neededColumns.append(i)
            print(neededColumns)
            # file = File
            # ready_to_use_prices = pricesCollector(neededColumns, file)
            # return
        else:
            template = 'pricer.html'
            return render(request, template)
        print('after if loop, neededColumns: ', neededColumns)
    # https://docs.djangoproject.com/en/3.0/ref/contrib/messages/
    return render(request, template)


def about_page(request):
    about_page_title = "Hey, i'm here to tell you about me"
    return render(request, 'home_page.html', {'title': about_page_title})


def easter_egg_page(request):
    print('before render, request: ', request)
    easter_egg_title = 'Wow, nice to see you here!'
    form = PricerForm()
    print(form)
    template = 'easter_egg.html'
    context = {
        "form": form
    }
    return render(request, template, context)

# def page_not_found(request, exception):
#     return render(request, '404.html', {'title': 'Sorry, looks like we are lost'})
#
#
# def error_500(request):
#     return render(request, '404.html', )

templates/base.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand">PB</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav"
          aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="http://127.0.0.1:8000/home/">Start <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="http://127.0.0.1:8000/pricer/">Add price</a>
      </li>
{#      <li class="nav-item">#}
{#        <a class="nav-link" href="http://127.0.0.1:8000/contacts/">Contacts</a>#}
{#      </li>#}
{#      <li class="nav-item">#}
{#        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>#}
{#      </li>#}
    </ul>
  </div>
</nav>

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>{% block head_title %}Replace this value{% endblock %} djPet</title>
  </head>
{#  <body class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">#}
{#  <header class="masthead mb-auto"></header>#}
    <h1>{{  title }}</h1>
    {% block content %}
    Replace this value
    {% endblock %}
{#  <footer class="mastfoot mt-auto">#}
{#      <div class="inner">#}
{#          <p class="text-center text-muted">some text with <a href="#" class="text-muted"> some link</a> </p>#}
{#      </div>#}
{#  </footer>#}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

templates/contacts.html
{% extends "base.html" %}

{% block head_title %}Links are here{% endblock %}

{% block content %}
<p>Github.com</p>
{% endblock %}

templates/easter_egg.html
{% extends "base.html" %}


{% block content %}
<form method="post" enctype="multipart/form-data">
{#    {{ form.as_p }}#}
        <div class="row mx-auto" style="height: 18rem">
{#            {{ form.non_field_errors }}#}
            <div class="col-md-2">
{#                <div class="fieldWrapper">#}
                    <div class="card border-primary" style="height: 12rem">
                        <div class="card-body">
                            <h5 class="card-title text-center"> Shop ID</h5>
                            <p> Fill in a number/letter of column with Shop ID</p>
                        </div>
        {#                    <p class="text-center"> Example: A </p>#}
                        <div class="card-footer bg-transparent">
                            <label for="id_shopID"></label>
                            <input id="id_shopID" type="text" name="shopID" placeholder="Example: A" required>

        {#                    <input type="submit>">#}
        {#                    <button type="submit">Confirm</button>#}
                        </div>
                    </div>
                </div>
            </div>
{#{{ form.non_field_errors }}#}
{#<div class="fieldWrapper">#}
{#    {{ form.shopID.errors }}#}
{#    <label for="{{ form.shopID.id_for_label }}"></label>#}
</div>
</form>
{% endblock %}

templates/home_page.html
{% extends 'base.html' %}
{% block head_title %}Home{% endblock %}
{%  block content %}
<p>Lets see what you are looking for</p>
{% endblock  %}

templates/pricer.html
{%  extends "base.html" %}

{% block head_title %}Pricer{% endblock %}

{% block content %}
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Attention block</h1>
    <p class="lead">This is the instruction how to work with this form. Please read carefully.</p>
      <ul class="list-group">
      <li class="list-group-item">1. File you want to download must be an Excel file (.xlx, .xmlx, .cvs) </li>
      <li class="list-group-item">2. You need to fill in numbers of columns which heed to extract</li>
      <li class="list-group-item">3. </li>
      <li class="list-group-item">4. </li>
      <li class="list-group-item">5. </li>
      </ul>
  </div>

</div>
{#    <form style="height: 8rem">#}
{#    <div class="input-group mb-3 col-sm-6 mx-auto">#}
{#      <div class="input-group-prepend">#}
{#        <span class="input-group-text " id="inputGroupFileAddon01">Upload</span>#}
{#      </div>#}
{#      <div class="custom-file">#}
{#        <input type="file" class="custom-file-input" id="inputGroupFile01" aria-describedby="inputGroupFileAddon01">#}
{#        <label class="custom-file-label" for="inputGroupFile01">Choose file</label>#}
{#      </div>#}
{#    </div>#}
{#    </form>#}

{# download file from user's PC #}
    <form method='post' enctype="multipart/form-data" style="height: 8rem">
    <div class="form-row mx-auto" style="width: 50%; height: 3rem">
        {% csrf_token %}
        <h3 class="lead text-center mx-auto">
            Upload file here
        </h3>
    </div>
    <div class="input-group form-row mx-auto bg-secondary" style="width: 50%">
        <div class="custom-file">
          <label class="custom-file-label" for="id_document">Choose file</label>
          <input type="file" name="document" class="custom-file-input" id="id_document"
               aria-describedby="id_document" required>
        </div>
    </div>
{#    </form>#}

{# place for download file via URL-link #}

{#    <div class="container" style="width: 95%">#}
    <div class="form-row mx-auto" style="width: 50%; height: 3rem">
    <h2 class="lead text-center mx-auto"> Define needed information here</h2>
    </div>

{#    <form method="POST" action="."> {% csrf_token %}#}
    <div class="row mx-auto" style="height: 18rem">
        <div class="col-md-2">
            <div class="card border-primary" style="height: 13rem">
                <div class="card-body">
                    <h5 class="card-title text-center"> Shop ID</h5>
                    <p> Fill in a number/letter of column with Shop ID</p>
                </div>
{#                    <p class="text-center"> Example: A </p>#}
                <div class="card-footer bg-transparent">
                    <label for="id_shopID"></label>
                    <input type="text" class="form-control" name="shopID" id="id_shopID" placeholder="Example: A" required>
{#                    <input type="submit>">#}
{#                    <button type="submit">Confirm</button>#}
                </div>
            </div>
        </div>
        <div class="col-md-2">
            <div class="card border-info" style="height:13rem">
                <div class="card-body">
                    <h5 class="card-title text-center">Name</h5>
                    <p> Number/letter of full name of a good column</p>
                </div>
{#                    <p> Example: B </p>#}
                <div class="card-footer bg-transparent">
                    <label for="id_name"></label>
                    <input type="text" class="form-control" name="name" id="id_name" placeholder="Example: B" required>
{#                    <div class="invalid-feedback">#}
{#                        This field mustn't be emtpy#}
{#                    </div>#}
{#                    <botton type="submit">Confirm</botton>#}
                </div>
            </div>
        </div>
        <div class="col-md-2">
            <div class="card border-primary" style="height: 13rem">
                <div class="card-body">
                    <h5 class="card-title"> Amount</h5>
                    <p> Wrote a number/letter of a column with amount.</p>
                </div>
{#                    <p> Example: C </p>#}
                <div class="card-footer bg-transparent">
                    <label for="inputAmount"></label>
                    <input type="text" class="form-control" name="amount" id="inputAmount" placeholder="Example: C" required>
{#                    <button type="submit">Confirm</button>#}
                </div>
            </div>
        </div>
        <div class="col-md-2">
            <div class="card border-info" style="height: 13rem">
                <div class="card-body">
                    <h5 class="card-title">Price</h5>
                    <p class="card-text">Write a number/letter of column with purchase price.</p>
{#                    <p> Example: D </p>#}
                </div>
                <div class="card-footer bg-transparent">
                    <label for="inputPrice"></label>
                    <input type="text" class="form-control" name="price" id="inputPrice" placeholder="Example: D" required>
{#                    <buttom type="submit">Confirm</buttom>#}
                </div>
            </div>
        </div>
        <div class="col-md-2">
            <div class="card border-primary" style="height: 13rem">
                <div class="card-body">
                    <h5 class="card-title">Part Number</h5>
                    <p> Fill in this field with number/letter of column with PN.</p>
                </div>
{#                    <p> Example: E </p>#}
                <div class="card-footer bg-transparent">
                    <label for="inputPN"></label>
                    <input type="text" class="form-control" name="partNumber" id="inputPN" placeholder="Example: E" required>
{#                    <button type="submit">Confirm</button>#}
                </div>
            </div>
        </div>
        <div class="col-md-2">
            <div class="card border-info" style="height: 13rem">
                <div class="card-body">
                    <h5 class="card-title">Minimal Retail Price</h5>
                    <p class="card-text"> Write a number/letter of MRC column</p>
                </div>
{#                    <p> Example: F </p>#}
                    <div class="card-footer bg-transparent">
                        <label for="inputMRC"></label>
                        <input type="text" class="form-control" name="MRP" id="inputMRC" placeholder="Example: F" required>
{#                    <button type="submit">Confirm</button>#}
                    </div>
            </div>
        </div>
{#    </div>#}
    </div>
        <div class="row-cols-1 mx-auto text-center" style="height: 8rem">
            <button type="submit" class="btn btn-primary btn-lg" style='width: 15%'>Start forming price list</button>
        </div>
    </form>


{% endblock %}

templates/success_download.html
{% extends "base.html" %}